name: publish_mason_brick
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  actions_toolkit_dart:
    git:
      url: https://github.com/abitofevrything/actions-toolkit-dart
      ref: feat/environment-state-output
  checked_yaml: ^2.0.1
  collection: ^1.17.0
  mason: ^0.1.0-dev.39
  mason_api: ^0.1.0-dev.8
  path: ^1.8.2
  pub_semver: ^2.1.3
