name: Action test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        uses: abitofevrything/publish-mason-brick@master
        with:
          path: test_brick
          dryRun: true
          email: ${{ secrets.TEST_EMAIL }}
          password: ${{ secrets.TEST_PASSWORD }}
